### ISSUE TITLE
Origin games through Steam are not working

### ISSUE THREAD

**Issue by CygnusTerminal** [DeepDoge/discord-steam-proton-rpc#2]
When using this tool with Origin games through Steam (Dragon Age Inquisition in this case) it fails with this error spammed on the console
```
Process filename: /home/voivod/.local/share/Steam/steamapps/__common_hidden__discord-steam-proton-rpc/Proton 7.0/dist/bin/wineserver
Process commandline: /home/voivod/.local/share/Steam/steamapps/__common_hidden__discord-steam-proton-rpc/Proton 7.0/dist/bin/wineserver
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at MyApp.Program.<>c__DisplayClass0_0.<Main>g__task|0()

```

**Comment by DeepDoge** [comment]
I tried fix the bug in your log.
But couldn't test it because I don't have enough space to download it on my laptop.
You can test it if you want to: https://github.com/DeepDoge/discord-steam-proton-rpc/releases/tag/release-6
I will test it on my system later.
